# This is the source root /path/to/RetroGames/
BASE_RA_PATH="emulators/RetroArch/_base_/RetroArch"
BASE_NS_PATH="emulators/RetroArch/Nintendo Switch/RetroArch.Full"

# Android: should replace XXXX-XXXX to your real SD card ID
# Windows: not need to replace '/' to '\\' global.
# Switch: not supports Chinese filename, for making sure it works right,
# we need to `bash hack/update-switch-rom`
# should not have space after ',', this will cause some error
platforms=(
    # platform, default_path_prefix
    # 'Android,/storage/XXXX-XXXX/RetroArch/@ROM'
    # 'Apple IOS,~/Documents/RetroArch/@ROM'
    # 'Nintendo Switch,/retroarch/@ROM'
    # 'Sony PSV,ux0:/data/retroarch/@ROM'
    'Windows,@ROM'
)

emulators=(
    '3DO'
    '3DS'
    'ATARI2600'
    'ATARI5200'
    'ATARI7800'
    'DC'
    'DC hack'
    'DOS'
    'FBA ACT hack'
    'FBNEO ACT'
    'FBNEO ACT V'
    'FBNEO ACT hack1'
    'FBNEO ACT hack2'
    'FBNEO ETC'
    'FBNEO ETC V'
    'FBNEO FLY'
    'FBNEO FLY V'
    'FBNEO FTG'
    'FBNEO FTG hack'
    'FBNEO RAC'
    'FBNEO STG'
    'FBNEO STG V'
    'FBNEO STG hack'
    'FC'
    'FC hack'
    'FC-HD'
    'GAME WATCH'
    'GB'
    'GBA'
    'GBC'
    'GG'
    'LIGHT GUN'
    'LYNX'
    'MAME ACT'
    'MAME ETC'
    'MAME FLY'
    'MAME FLY V'
    'MAME FTG'
    'MAME FTG hack'
    'MAME RAC'
    'MAME STG'
    'MAME STG V'
    'MD'
    'MD hack'
    'MD hack(picodrive)'
    'MD-32X'
    'MD-CD'
    'N64'
    'NAOMI'
    'NDS'
    'NEOGEO-CD'
    'NGC'
    'NGPC'
    'PC-FX'
    'PCE'
    'PCE-CD'
    'POKE MINI'
    'PS1'
    'PS1 hack'
    'PS2'
    'PS2 hack'
    'SFC'
    'SFC hack'
    'SFC-MSU1'
    'SMS'
    'SS'
    'SS plus'
    'Virtual Boy'
    'WII Ware'
    'WS'
    'WSC'
    'psp'
)
